export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_FAILED = 'FETCH_FAILED';
export const SET_INITIAL_TOTAL = 'SET_INITIAL_TOTAL';
export const SET_INGREDIENTS_PRICES = 'SET_INGREDIENTS_PRICES';

export const PURCHASE_BURGUER_START = 'PURCHASE_BURGUER_START';
export const PURCHASE_BURGUER_SUCCESS = 'PURCHASE_BURGUER_SUCCESS';
export const PURCHASE_BURGUER_FAILED = 'PURCHASE_BURGUER_FAILED';
export const PURCHASE_BURGUER_INIT = 'PURCHASE_BURGUER_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';